name: .NET

on:
  push:
    branches: [ master, web-service ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./BlipBloopBot.sln
    - name: Build
      run: dotnet build --no-restore ./BlipBloopBot.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./BlipBloopBot.sln
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./BlipBloopBot
      run: dotnet restore
    - name: Build
      working-directory: ./BlipBloopBot
      run: dotnet build --no-restore
    - name: Publish
      working-directory: ./BlipBloopBot
      run: dotnet publish --self-contained true -r win10-x64 -o publish
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: |
          ./BlipBloopBot/publish
