name: .NET

on:
  push:
    branches: [ master, web-service ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Restore dependencies
      run: dotnet restore ./BlipBloopBot.sln
    - name: Build
      run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true ./BlipBloopBot.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./BlipBloopBot.sln
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Restore dependencies
      working-directory: ./BlipBloopBot
      run: dotnet restore
    - name: Build
      working-directory: ./BlipBloopBot
      run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true
    - name: Publish
      working-directory: ./BlipBloopBot
      run: dotnet publish --self-contained true -r win-x64 -o publish -p:ContinuousIntegrationBuild=true
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: |
          ./BlipBloopBot/publish
