name: NuGet

on:
  workflow_run:
    workflows: [ ".NET" ]
    branches:
      - master
    types: 
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Restore dependencies
      run: dotnet restore ./BlipBloopBot.sln
    - name: Build
      run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true ./BlipBloopBot.sln
    - name: Publish Conceptoire.Twitch.Abstractions
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: waldosax/publish-nuget@95f8e50d8df92e9bafae7188c5345a3534774d94
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Conceptoire.Twitch.Abstractions/Conceptoire.Twitch.Abstractions.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
    - name: Publish Conceptoire.Twitch
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: waldosax/publish-nuget@95f8e50d8df92e9bafae7188c5345a3534774d94
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Conceptoire.Twitch/Conceptoire.Twitch.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
